### ISSUE TITLE
Modernizr dependency requirement has no version!

### ISSUE THREAD

**Issue by dreamyguy** [doctyper/customizr#9]
Listing Modernizr dependency in the way that's done [here](https://github.com/doctyper/customizr/blob/8dc2fb7a9e28b1a57bb019e97a9339d94ea8c2f9/package.json#L34) is very bad practice, it just broke our environment.

I don't know the reasoning behind it, but couldn't we just point to a version instead?

`Customizr` is part of [`gulp-modernizr`](gulp-modernizr), and that's the background for the error we got.

**Comment by dreamyguy** [comment]
For the sake of reference, the error was:
```
has no method 'map'
  at /<my-path>/node_modules/gulp-modernizr/node_modules/customizr/src/metadata.js:23:25
```

**Comment by doctyper** [comment]
I'm working on a solve. I would however like to point out that `gulp-modernizr` has not been published to npm, and is not ready for release. See #3.

This is pre-release code and you should not expect stability.

**Comment by dreamyguy** [comment]
Hi there Rich, a colleague pointed out that Modernizr doesn't make this too easy either (something about their tags not including a `package.json` file (?) ).

Ok, wasn't aware of #3, thanks for the heads up. We are reverting to getting `Modernizr` directly from `Bower` for the time being. Cheers! :beers:

**Comment by yamadapc** [comment]
@doctyper you can fix this by changing your `package.json` file to reference a known compatible commit hash. I'm not sure if this works, perfectly, but it solves the `metadata` errors:
```
    "modernizr": "git+https://github.com/Modernizr/Modernizr#a4e41038d850572bc1b02d2fbe1bbffb7b01dbd4",
```

**Comment by doctyper** [comment]
Pending Modernizr/Modernizr#1521

**Comment by doctyper** [comment]
Fixed in b037e2269492ba83dcc561f3fadf6d6b9305922a. [Passing all tests](https://travis-ci.org/doctyper/customizr/builds/50235214).

**Comment by yamadapc** [comment]
Awesome; thanks.

**Comment by mahnunchik** [comment]
Thanks!

But `gulp-modernizr` already in npm https://www.npmjs.com/package/gulp-modernizr

**Comment by doctyper** [comment]
Wow. That is not cool.

**Comment by doctyper** [comment]
@metalshark you are not a maintainer of either [customizr](https://www.npmjs.com/package/customizr), [gulp-modernizr](https://www.npmjs.com/package/gulp-modernizr), or [modernizr](https://www.npmjs.com/package/modernizr). Please unpublish these repositories from npm.

**Comment by metalshark** [comment]
Agreed I am not - removing them straight away now

**Comment by mahnunchik** [comment]
@doctyper or for examle @metalshark can move access rights

**Comment by metalshark** [comment]
Is there an easy way for me to remove or move over rights? I wanted to get
the packages so they were easily available. Going through the "npm
unpublish" literature now.

**Comment by mahnunchik** [comment]
@doctyper @metalshark @yamadapc unpublishing can cause a lot of broken builds (and produces a lot of issue)

**Comment by metalshark** [comment]
@mahnunchik I am ready and willing how would you like me to proceed?

**Comment by mahnunchik** [comment]
@metalshark You can make @doctyper owner of `customizr` and `gulp-modernizr`. He will be able to remove you from owners.

Documentation here https://docs.npmjs.com/cli/owner

@doctyper @patrickkettner who should be owner of @Modernizr ?

**Comment by patrickkettner** [comment]
Thank you @mahnunchik!

for the moment, I can take control of modernizr. we can discuss internally as to how to proceed longterm

**Comment by metalshark** [comment]
@mahnunchik @doctyper should now be the owner of customizr and gulp-modernizr

**Comment by metalshark** [comment]
@patrickkettner I've got to go in the next 5 minutes and wont be able to do much Internet wise for a few hours - is it ok if I add you as an owner for Modernizr? You can take it from there.

**Comment by patrickkettner** [comment]
yep!

**Comment by metalshark** [comment]
@patrickkettner Done!

**Comment by mahnunchik** [comment]
:+1:

**Comment by dreamyguy** [comment]
@yamadapc thanks for the suggestion, @doctyper thanks for the fast fix! :8ball:
